version: "3.8"

services:
  oracle:
    image: gvenzl/oracle-free:latest
    container_name: oracle-bancario
    ports:
      - "1521:1521"
    environment:
      ORACLE_PASSWORD: Alfredo+123
      ORACLE_DATABASE: BANCARIO_DB
      APP_USER: BANCARIO
      APP_USER_PASSWORD: Alfredo+123
    volumes:
      - ./init.sql:/container-entrypoint-startdb.d/init.sql:ro
      - oracle_data:/opt/oracle/oradata
    healthcheck:
      test: ["CMD", "healthcheck.sh"]
      interval: 30s
      timeout: 10s
      retries: 10

volumes:
  oracle_data:
